import type { Metadata } from "next";
import "../globals.css";
import "@/assets/styles/main.scss"
import '@mantine/core/styles.css';
import { Toaster } from 'react-hot-toast'
import { createTheme, MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
        <div className='w-full flex justify-center h-[100vh] items-center bg-white'>
          <Toaster />
          {children}
        </div>
        </MantineProvider>
      </body>
    </html>
  );
}
