import type { Metadata } from "next";
import "../globals.css";
import "@/assets/styles/main.scss"
import '@mantine/core/styles.css';
import RootDashboardLayout from "@/components/app/wrapper/LayoutWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootAppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RootDashboardLayout>
      {children}
    </RootDashboardLayout>
  );
}
